apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-server
  labels:
    app: admission-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-server
  template:
    metadata:
      labels:
        app: admission-server
    spec:
      containers:
      - name: server
        image: douglasmakey/admissioncontroller:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/certs
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: admission-tls
---
apiVersion: v1
kind: Service
metadata:
  name: admission-server
spec:
  selector:
    app: admission-server
  ports:
    - port: 443
      targetPort: 8443